# Generated by Django 4.2.5 on 2024-11-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('tipos', models.CharField(choices=[('administrativo', 'Administrativo'), ('directo', 'Directo'), ('indirecto', 'Indirecto')], max_length=15)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='ri_rh_puest_nombre_0b3fc6_idx'), models.Index(fields=['tipos'], name='ri_rh_puest_tipos_dee6e0_idx')],
            },
        ),
    ]
