# Generated by Django 4.2.5 on 2024-11-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('identificacion_oficial', models.FileField(upload_to='Identificacion/')),
                ('fecha_nacimiento', models.DateField()),
                ('acta_nacimiento', models.FileField(upload_to='ActaNacimiento/')),
                ('escolaridad', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('universidad', 'Universidad'), ('postgrado', 'Postgrado')], max_length=15)),
                ('constancia_estudio', models.FileField(upload_to='ConstanciaEstudio/')),
                ('salario_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clabe_interbancaria', models.CharField(max_length=18)),
                ('estado_cuenta', models.FileField(upload_to='EstadosDeCuentas/')),
                ('numero_contacto', models.CharField(max_length=15)),
                ('contacto_emergencia', models.CharField(max_length=15)),
                ('rfc', models.CharField(max_length=13)),
                ('constancia_situacion_fiscal', models.FileField(upload_to='ConstanciaSituacionFiscal/')),
                ('curp', models.CharField(max_length=18)),
                ('pdf_curp', models.FileField(upload_to='CURP/')),
                ('numero_seguro_social', models.CharField(max_length=11)),
                ('comprobante_nss', models.FileField(upload_to='NSS/')),
                ('alta_imss', models.FileField(blank=True, null=True, upload_to='AltaIMSS/')),
                ('direccion_completa', models.TextField()),
                ('comprobante_domicilio', models.FileField(upload_to='ComprobanteDeDomicilio/')),
                ('monto_retencion_infonavit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aviso_retencion_infonavit', models.FileField(upload_to='AvisoDeRetencionInfonavit/')),
                ('carta_recomendacion_1', models.FileField(upload_to='CartasDeRecomendacion/')),
                ('carta_recomendacion_2', models.FileField(upload_to='CartasDeRecomendacion/')),
                ('carta_recomendacion_3', models.FileField(upload_to='CartasDeRecomendacion/')),
                ('carta_no_antecedentes_penales', models.FileField(upload_to='CartaDeNoAntecedentesPenales/')),
                ('contrato_laboral', models.FileField(upload_to='ContratoLaboral/')),
                ('curriculum_vitae', models.FileField(upload_to='CurriculumVitae/')),
                ('carta_oferta', models.FileField(blank=True, null=True, upload_to='CartaOferta/')),
                ('examen_medico', models.FileField(upload_to='ExamenMedico/')),
                ('carta_renuncia', models.FileField(blank=True, null=True, upload_to='CartaRenuncia/')),
                ('finiquito_firmado', models.FileField(blank=True, null=True, upload_to='FiniquitoFirmado/')),
                ('baja_imss', models.FileField(blank=True, null=True, upload_to='BajaImss/')),
                ('comprobante_transferencia_finiquito', models.FileField(blank=True, null=True, upload_to='ComprobanteTransferenciaFiniquito/')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('proceso_finiquito', 'Proceso Finiquito'), ('finiquitado', 'Finiquitado')], default='activo', max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ri_rh.puesto')),
            ],
        ),
    ]
