# Generated by Django 4.2.5 on 2024-11-15 17:23

from django.db import migrations, models
import django.db.models.deletion
import ri_rh.models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0002_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='acta_nacimiento',
            field=models.FileField(upload_to='DocumentosEmpleado/ActaNacimiento/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='alta_imss',
            field=models.FileField(blank=True, null=True, upload_to='DocumentosEmpleado/AltaIMSS/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='aviso_retencion_infonavit',
            field=models.FileField(upload_to='DocumentosEmpleado/AvisoDeRetencionInfonavit/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='baja_imss',
            field=models.FileField(blank=True, null=True, upload_to='DocumentosEmpleado/BajaImss/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='carta_no_antecedentes_penales',
            field=models.FileField(upload_to='DocumentosEmpleado/CartaDeNoAntecedentesPenales/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='carta_oferta',
            field=models.FileField(blank=True, null=True, upload_to='DocumentosEmpleado/CartaOferta/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='carta_recomendacion_1',
            field=models.FileField(upload_to='DocumentosEmpleado/CartasDeRecomendacion/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='carta_recomendacion_2',
            field=models.FileField(upload_to='DocumentosEmpleado/CartasDeRecomendacion/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='carta_recomendacion_3',
            field=models.FileField(upload_to='DocumentosEmpleado/CartasDeRecomendacion/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='carta_renuncia',
            field=models.FileField(blank=True, null=True, upload_to='DocumentosEmpleado/CartaRenuncia/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='comprobante_domicilio',
            field=models.FileField(upload_to='DocumentosEmpleado/ComprobanteDeDomicilio/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='comprobante_nss',
            field=models.FileField(upload_to='DocumentosEmpleado/NSS/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='comprobante_transferencia_finiquito',
            field=models.FileField(blank=True, null=True, upload_to='DocumentosEmpleado/ComprobanteTransferenciaFiniquito/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='constancia_estudio',
            field=models.FileField(upload_to='DocumentosEmpleado/ConstanciaEstudio/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='constancia_situacion_fiscal',
            field=models.FileField(upload_to='DocumentosEmpleado/ConstanciaSituacionFiscal/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contrato_laboral',
            field=models.FileField(upload_to='DocumentosEmpleado/ContratoLaboral/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='curriculum_vitae',
            field=models.FileField(upload_to='DocumentosEmpleado/CurriculumVitae/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_cuenta',
            field=models.FileField(upload_to='DocumentosEmpleado/EstadosDeCuentas/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='examen_medico',
            field=models.FileField(upload_to='DocumentosEmpleado/ExamenMedico/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='finiquito_firmado',
            field=models.FileField(blank=True, null=True, upload_to='DocumentosEmpleado/FiniquitoFirmado/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='identificacion_oficial',
            field=models.FileField(upload_to='DocumentosEmpleado/Identificacion/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pdf_curp',
            field=models.FileField(upload_to='DocumentosEmpleado/CURP/'),
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('actas_administrativas', 'Actas Administrativas'), ('antidoping', 'Antidopings'), ('aumento_sueldo', 'Aumento de Sueldo'), ('capacitaciones', 'Capacitaciones'), ('descuento_pension', 'Descuento de Pensión Alimenticia'), ('uniforme_seguridad', 'Entrega de Uniforme y Seguridad'), ('vacaciones', 'Vacaciones'), ('aguinaldo', 'Pago de Aguinaldo'), ('prima_vacacional', 'Prima Vacacional'), ('prestaciones', 'Prestaciones'), ('ptu', 'PTU'), ('incapacidades', 'Incapacidades'), ('recibo_nomina', 'Recibo de Nómina'), ('entradas_salidas', 'Entradas y Salidas')], max_length=50)),
                ('archivo', models.FileField(upload_to=ri_rh.models.documento_upload_path)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ri_rh.empleado')),
            ],
        ),
    ]
