# Generated by Django 4.2.5 on 2024-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0003_alter_empleado_acta_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('direccion', models.TextField()),
                ('numero_contacto', models.CharField(max_length=15)),
            ],
        ),
    ]
