# Generated by Django 4.2.5 on 2024-11-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0004_universidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticanteResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('identificacion_oficial', models.FileField(upload_to='PracticantesResidentes/Identificacion/')),
                ('tipo', models.CharField(choices=[('practicante', 'Practicante'), ('residente', 'Residente')], max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('acta_nacimiento', models.FileField(upload_to='PracticantesResidentes/ActaNacimiento/')),
                ('salario_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clabe_interbancaria', models.CharField(max_length=18)),
                ('estado_cuenta', models.FileField(upload_to='PracticantesResidentes/EstadosDeCuenta/')),
                ('numero_contacto', models.CharField(max_length=15)),
                ('contacto_emergencia', models.CharField(max_length=15)),
                ('rfc', models.CharField(max_length=13)),
                ('pdf_rfc', models.FileField(upload_to='PracticantesResidentes/RFC/')),
                ('curp', models.CharField(max_length=18)),
                ('pdf_curp', models.FileField(upload_to='PracticantesResidentes/CURP/')),
                ('numero_seguro_social', models.CharField(max_length=11)),
                ('pdf_numero_seguro_social', models.FileField(upload_to='PracticantesResidentes/SeguroSocial/')),
                ('direccion_completa', models.TextField()),
                ('comprobante_domicilio', models.FileField(upload_to='PracticantesResidentes/ComprobanteDomicilio/')),
                ('carta_presentacion', models.FileField(upload_to='PracticantesResidentes/CartaPresentacion/')),
                ('curriculum_vitae', models.FileField(upload_to='PracticantesResidentes/CurriculumVitae/')),
                ('estado', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicantes_residentes', to='ri_rh.puesto')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicantes_residentes', to='ri_rh.universidad')),
            ],
        ),
    ]
