# Generated by Django 4.2.5 on 2024-11-15 19:41

from django.db import migrations, models
import django.db.models.deletion
import ri_rh.models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0005_practicanteresidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('practicante', 'Practicante'), ('residente', 'Residente')], max_length=15)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('obligatorio', models.BooleanField(default=False)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_catalogo', to='ri_rh.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=ri_rh.models.documento_cargado_upload_path)),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('catalogo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cargados', to='ri_rh.catalogodocumento')),
                ('practicante_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cargados', to='ri_rh.practicanteresidente')),
            ],
        ),
    ]
