# Generated by Django 4.2.5 on 2024-12-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0006_catalogodocumento_documentocargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.IntegerField()),
                ('subsidio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tiempo_extra', models.IntegerField(null=True)),
                ('vale_despensa', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vale_gasolina', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
