# Generated by Django 4.2.5 on 2024-12-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0007_nominas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nominas',
        ),
    ]
