# Generated by Django 4.2.5 on 2024-12-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0008_delete_nominas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicanteresidente',
            name='numero_contacto',
            field=models.CharField(max_length=80),
        ),
    ]
