# Generated by Django 4.2.5 on 2024-12-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0009_alter_practicanteresidente_numero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_contacto',
            field=models.CharField(max_length=80),
        ),
    ]
