# Generated by Django 4.2.5 on 2024-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0010_alter_empleado_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_contacto',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='practicanteresidente',
            name='numero_contacto',
            field=models.CharField(max_length=15),
        ),
    ]
