# Generated by Django 4.2.5 on 2025-01-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0011_alter_empleado_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicanteresidente',
            name='contacto_emergencia',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='practicanteresidente',
            name='numero_contacto',
            field=models.CharField(max_length=80),
        ),
    ]
