# Generated by Django 4.2.5 on 2025-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0012_alter_practicanteresidente_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_contacto',
            field=models.CharField(max_length=80),
        ),
    ]
