# Generated by Django 4.2.5 on 2025-04-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_rh', '0013_alter_empleado_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRequisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfRequisitosDocumentacion', models.FileField(upload_to='DocumentosRequisitos/')),
            ],
        ),
    ]
